// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/email-sig/Bold.tsx": () => import("../components/mockups/email-sig/Bold.tsx"),
  "./components/mockups/email-sig/Compact.tsx": () => import("../components/mockups/email-sig/Compact.tsx"),
  "./components/mockups/email-sig/Moderate.tsx": () => import("../components/mockups/email-sig/Moderate.tsx")
};
